### ISSUE TITLE
Cannot install SurvLIMEpy

### ISSUE THREAD

**Issue by psads-git** [imatge-upc/SurvLIMEpy#22]
I am trying to install  `SurvLIMEpy` on a Linux machine, but getting the following errors. Any help?

Thanks in advance!

```
$ /home/x/.virtualenvs/r-reticulate/bin/pip install SurvLIMEpy
Collecting SurvLIMEpy
  Using cached survlimepy-0.0.10-py3-none-any.whl (65 kB)
Requirement already satisfied: numpy in ./.virtualenvs/r-reticulate/lib64/python3.11/site-packages (from SurvLIMEpy) (1.25.0)
Requirement already satisfied: cvxpy in ./.virtualenvs/r-reticulate/lib64/python3.11/site-packages (from SurvLIMEpy) (1.3.1)
Collecting scikit-survival==0.18.0 (from SurvLIMEpy)
  Using cached scikit-survival-0.18.0.tar.gz (2.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [110 lines of output]
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  free(self.riskset_left)
      
          def __reduce__(self):
              return (type(self), (self.n_outputs, self.n_samples, self.event_times), self.__getstate__())
      
          cdef int init(self, const DOUBLE_t[:, ::1] y, DOUBLE_t* sample_weight,
              ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:131:9: Signature not compatible with previous declaration
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          # The criterion object is maintained such that left and right collected
          # statistics correspond to samples[start:pos] and samples[pos:end].
      
          # Methods
          cdef int init(
                      ^
      ------------------------------------------------------------
      
      /tmp/pip-build-env-t_oxqvhj/overlay/lib64/python3.11/site-packages/sklearn/tree/_criterion.pxd:44:17: Previous declaration is here
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef Riskset * riskset_total
          cdef Riskset * riskset_left
      
          def __cinit__(self, SIZE_t n_outputs, SIZE_t n_samples, const DOUBLE_t[::1] event_times):
              # Default values
              self.sample_weight = NULL
                                  ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:102:29: Cannot convert 'void *' to memoryviewslice
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                        SIZE_t end) nogil except -1:
              """Initialize the criterion at node samples[start:end] and
                 children samples[start:start] and samples[start:end]."""
              # Initialize fields
              self.y = y
              self.sample_weight = sample_weight
                                  ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:138:29: Cannot convert 'DOUBLE_t *' to memoryviewslice
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self.pos = self.end
              return 0
      
          cdef int update(self, SIZE_t new_pos) nogil except -1:
              """Updated statistics by moving samples[pos:new_pos] to the left."""
              cdef const double* sample_weight = self.sample_weight
                                                    ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:209:47: Cannot assign type 'const DOUBLE_t[:]' to 'const double *'
      Compiling sksurv/bintrees/_binarytrees.pyx because it changed.
      Compiling sksurv/kernels/_clinical_kernel.pyx because it changed.
      Compiling sksurv/ensemble/_coxph_loss.pyx because it changed.
      Compiling sksurv/svm/_prsvm.pyx because it changed.
      Compiling sksurv/svm/_minlip.pyx because it changed.
      Compiling sksurv/tree/_criterion.pyx because it changed.
      Compiling sksurv/linear_model/_coxnet.pyx because it changed.
      [1/7] Cythonizing sksurv/bintrees/_binarytrees.pyx
      [2/7] Cythonizing sksurv/ensemble/_coxph_loss.pyx
      [3/7] Cythonizing sksurv/kernels/_clinical_kernel.pyx
      [4/7] Cythonizing sksurv/linear_model/_coxnet.pyx
      [5/7] Cythonizing sksurv/svm/_minlip.pyx
      [6/7] Cythonizing sksurv/svm/_prsvm.pyx
      [7/7] Cythonizing sksurv/tree/_criterion.pyx
      Traceback (most recent call last):
        File "/home/x/.virtualenvs/r-reticulate/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/x/.virtualenvs/r-reticulate/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/x/.virtualenvs/r-reticulate/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-t_oxqvhj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-t_oxqvhj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-t_oxqvhj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 222, in <module>
        File "<string>", line 195, in setup_package
        File "<string>", line 175, in get_extensions
        File "<string>", line 139, in cythonize_extensions
        File "/tmp/pip-build-env-t_oxqvhj/overlay/lib64/python3.11/site-packages/Cython/Build/Dependencies.py", line 1115, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-t_oxqvhj/overlay/lib64/python3.11/site-packages/Cython/Build/Dependencies.py", line 1238, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: sksurv/tree/_criterion.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
$

```

**Comment by CarlosHernandezP** [comment]
Thanks for reaching out!

I tried installing `survlimepy` on a brand new virtual environment (on Linux OS) with:

`pip install survlimepy` and I did not get any errors.

Some plausible solutions cross my mind:


1. Try installing it on a new virtual environment. If this does not fail maybe it has something there are conflicting packages on your current environment.
2. Try installing `ctyhon` separately with `pip install --upgrade cython`.
3. Ensure in advance that you have the correct version of `scikit survival` with `pip install scikit-survival==0.18.0`.

Let me know if any of these solve your problem!

**Comment by CarlosHernandezP** [comment]
Where you able to solve this?

**Comment by psads-git** [comment]
I am sorry, Carlos, for being late with my reply, but I have been quite busy recently.

I have tried all your suggestion, but with no success. (The errors are reported below.)

I am using:

- Fedora Linux 38.
- Python 3.11.4.
- Cython-0.29.36.
- Scikit-survival-0.18.0.

Thanks, Carlos!

```
$ /home/x/myenv/bin/pip install --upgrade pip
Requirement already satisfied: pip in ./myenv/lib64/python3.11/site-packages (22.3.1)
Collecting pip
  Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Successfully installed pip-23.1.2
[x@localhost ~]$ /home/x/myenv/bin/pip install survlimepy
Collecting survlimepy
  Using cached survlimepy-0.0.10-py3-none-any.whl (65 kB)
Collecting numpy (from survlimepy)
  Using cached numpy-1.25.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.6 MB)
Collecting cvxpy (from survlimepy)
  Using cached cvxpy-1.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)
Collecting scikit-survival==0.18.0 (from survlimepy)
  Using cached scikit-survival-0.18.0.tar.gz (2.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [222 lines of output]
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  free(self.riskset_left)
      
          def __reduce__(self):
              return (type(self), (self.n_outputs, self.n_samples, self.event_times), self.__getstate__())
      
          cdef int init(self, const DOUBLE_t[:, ::1] y, DOUBLE_t* sample_weight,
              ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:131:9: Signature not compatible with previous declaration
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          # The criterion object is maintained such that left and right collected
          # statistics correspond to samples[start:pos] and samples[pos:end].
      
          # Methods
          cdef int init(
                      ^
      ------------------------------------------------------------
      
      /tmp/pip-build-env-w1e61y0a/overlay/lib64/python3.11/site-packages/sklearn/tree/_criterion.pxd:47:17: Previous declaration is here
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef Riskset * riskset_total
          cdef Riskset * riskset_left
      
          def __cinit__(self, SIZE_t n_outputs, SIZE_t n_samples, const DOUBLE_t[::1] event_times):
              # Default values
              self.sample_weight = NULL
                                  ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:102:29: Cannot convert 'void *' to memoryviewslice
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          def __cinit__(self, SIZE_t n_outputs, SIZE_t n_samples, const DOUBLE_t[::1] event_times):
              # Default values
              self.sample_weight = NULL
      
              self.samples = NULL
                            ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:104:23: Cannot convert 'void *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                        SIZE_t end) nogil except -1:
              """Initialize the criterion at node samples[start:end] and
                 children samples[start:start] and samples[start:end]."""
              # Initialize fields
              self.y = y
              self.sample_weight = sample_weight
                                  ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:138:29: Cannot convert 'DOUBLE_t *' to memoryviewslice
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              """Initialize the criterion at node samples[start:end] and
                 children samples[start:start] and samples[start:end]."""
              # Initialize fields
              self.y = y
              self.sample_weight = sample_weight
              self.samples = samples
                 ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:139:12: Assignment of Python object not allowed without gil
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              """Initialize the criterion at node samples[start:end] and
                 children samples[start:start] and samples[start:end]."""
              # Initialize fields
              self.y = y
              self.sample_weight = sample_weight
              self.samples = samples
                            ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:139:23: Cannot convert 'SIZE_t *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self.pos = self.end
              return 0
      
          cdef int update(self, SIZE_t new_pos) nogil except -1:
              """Updated statistics by moving samples[pos:new_pos] to the left."""
              cdef const double* sample_weight = self.sample_weight
                                                    ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:209:47: Cannot assign type 'const DOUBLE_t[:]' to 'const double *'
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              return 0
      
          cdef int update(self, SIZE_t new_pos) nogil except -1:
              """Updated statistics by moving samples[pos:new_pos] to the left."""
              cdef const double* sample_weight = self.sample_weight
              cdef const SIZE_t* samples = self.samples
                                              ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:210:41: Cannot convert Python object to 'const SIZE_t *'
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              """Initialize the criterion at node samples[start:end] and
                 children samples[start:start] and samples[start:end]."""
              # Initialize fields
              self.y = y
              self.sample_weight = sample_weight
              self.samples = samples
                 ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:139:12: Accessing Python attribute not allowed without gil
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              """Initialize the criterion at node samples[start:end] and
                 children samples[start:start] and samples[start:end]."""
              # Initialize fields
              self.y = y
              self.sample_weight = sample_weight
              self.samples = samples
                            ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:139:23: Converting to Python object not allowed without gil
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              return 0
      
          cdef int update(self, SIZE_t new_pos) nogil except -1:
              """Updated statistics by moving samples[pos:new_pos] to the left."""
              cdef const double* sample_weight = self.sample_weight
              cdef const SIZE_t* samples = self.samples
                                              ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:210:41: Coercion from Python not allowed without the GIL
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              return 0
      
          cdef int update(self, SIZE_t new_pos) nogil except -1:
              """Updated statistics by moving samples[pos:new_pos] to the left."""
              cdef const double* sample_weight = self.sample_weight
              cdef const SIZE_t* samples = self.samples
                                              ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:210:41: Accessing Python attribute not allowed without gil
      Compiling sksurv/bintrees/_binarytrees.pyx because it changed.
      Compiling sksurv/kernels/_clinical_kernel.pyx because it changed.
      Compiling sksurv/ensemble/_coxph_loss.pyx because it changed.
      Compiling sksurv/svm/_prsvm.pyx because it changed.
      Compiling sksurv/svm/_minlip.pyx because it changed.
      Compiling sksurv/tree/_criterion.pyx because it changed.
      Compiling sksurv/linear_model/_coxnet.pyx because it changed.
      [1/7] Cythonizing sksurv/bintrees/_binarytrees.pyx
      [2/7] Cythonizing sksurv/ensemble/_coxph_loss.pyx
      [3/7] Cythonizing sksurv/kernels/_clinical_kernel.pyx
      [4/7] Cythonizing sksurv/linear_model/_coxnet.pyx
      [5/7] Cythonizing sksurv/svm/_minlip.pyx
      [6/7] Cythonizing sksurv/svm/_prsvm.pyx
      [7/7] Cythonizing sksurv/tree/_criterion.pyx
      Traceback (most recent call last):
        File "/home/x/myenv/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/x/myenv/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/x/myenv/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w1e61y0a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w1e61y0a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-w1e61y0a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 222, in <module>
        File "<string>", line 195, in setup_package
        File "<string>", line 175, in get_extensions
        File "<string>", line 139, in cythonize_extensions
        File "/tmp/pip-build-env-w1e61y0a/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1115, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-w1e61y0a/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1238, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: sksurv/tree/_criterion.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
$

```

**Comment by CarlosHernandezP** [comment]
I was able to reproduce your error my installing `Python 3.11`. There is an [issue in the `sksurv` GitHub](https://github.com/sebp/scikit-survival/issues/333) in which the authors say that `sksurv` has not yet been tested for `Python 3.11` 

I have found a [GitHub issue for sklearn](https://github.com/scikit-learn/scikit-learn/issues/24749) in which they solved the same problem (for sklearn) by typing the command:

`SETUPTOOLS_USE_DISTUTILS=stdlib`

But it did not work for me.

Apparently there are multiple problems that arise when installing certain libraries in `Python 3.11`:

https://stackoverflow.com/questions/74476152/error-in-installing-dlib-library-in-python3-11
https://github.com/scipy/scipy/issues/16988

For now I would advise downgrading to a more stable `python` version such as 3.8, 3.9 or 3.11. You can do so by `sudo apt install python3.9`. Installation should be straightforward from there.

**Comment by psads-git** [comment]
Thanks, Carlos, for your answer and your help!

**Comment by CarlosHernandezP** [comment]
I will be closing the issue for now. We will try to come back to it in the future once `Python 3.11` is more supported!

**Comment by bhuvighosh3** [comment]
Heyy I am still encountering this issue eventhough I used Python 3.9.23. How do I solve it?
